baseURL: 'https://cho0924.github.io/'
languageCode: ja
title: Cho
theme: PaperMod

defaultContentLanguage: ja

params:
  env: production
  defaultTheme: auto
  profileMode:
    enabled: true
    subtitle: "cho desu"
    imageUrl: "apple_c.jpg"
    imageTitle: "my icon"
    imageWidth: 200
    imageHeight: 200
